version: '2.0'
services:
  web:
    image: 'caleydo/ordino:starter'
    ports:
      - '8080:8080'
    environment:
      - PHOVEA_API_SERVER=api:9000
      - PHOVEA_NGINX_PORT=8080
    links:
      - api
  api:
    image: 'caleydo/ordino_server:starter'
    ports:
      - '9000:9000'
    volumes:
      - '.:/phovea_config'
    environment:
      - PHOVEA_CONFIG_PATH=/phovea_config/config.json
      - REDIS_HOST=clusterName.xxxxxx.regionAndAz.cache.amazonaws.com
      - REDIS_USERNAME=foo
      - REDIS_PASSWORD=bar
      - MONGO_HOST=sample-cluster.node.us-east-1.docdb.amazonaws.com
      - MONGO_USERNAME=foo
      - MONGO_PASSWORD=bar
