version: '2.0'
services:
  db_mongo:
    image: 'mongo:3.2'
    volumes:
      - 'db_mongo_data:/data/db'
  db_redis:
    image: 'redis:3.2-alpine'
    command: 'redis-server --appendonly yes'
    volumes:
      - 'db_redis_data:/data'
  web:
    image: 'caleydo/ordino:v5.3.0'
    ports:
      - '8080:80'
    environment:
      - PHOVEA_API_SERVER=api:9000
      - PHOVEA_NGINX_PORT=80
    links:
      - api
  api:
    image: 'caleydo/ordino_server:v5.3.0'
    ports:
      - '9000:9000'
    volumes:
      - '.:/phovea_config'
    environment:
      - PHOVEA_CONFIG_PATH=/phovea_config/config.json
    depends_on:
      - db_mongo
      - db_redis
      - db_publicdb
    links:
      - db_mongo
      - db_redis
      - 'db_publicdb:publicdb'
  db_publicdb:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_USER: publicdb
      POSTGRES_PASSWORD: publicdb
      POSTGRES_DB: publicdb
    volumes:
      - 'db_publicdb_data:/var/lib/postgresql/data'
  pgadmin4:
    image: thajeztah/pgadmin4
    depends_on:
      - db_publicdb
    links:
      - db_publicdb
    ports:
      - '5050:5050'
    volumes:
      - 'pgadmin4_data:/pgadmin'
volumes:
  db_mongo_data: null
  db_redis_data: null
  db_publicdb_data: null
  pgadmin4_data: null
