version: '2.0'
services:
  db_redis:
    image: 'redis:3.2-alpine'
    command: 'redis-server --appendonly yes'
    volumes:
      - 'db_redis_data:/data'
  web:
    image: 'caleydo/ordino:starter'
    ports:
      - '8080:80'
    environment:
      - PHOVEA_API_SERVER=api:9000
      - PHOVEA_NGINX_PORT=80
    links:
      - api
  api:
    image: 'caleydo/ordino_server:starter'
    ports:
      - '9000:9000'
    volumes:
      - '.:/phovea_config'
    environment:
      - PHOVEA_CONFIG_PATH=/phovea_config/config.json
    depends_on:
      - db_redis
    links:
      - db_redis
volumes:
  db_mongo_data: null
  db_redis_data: null
